In [2]:
import pandas as pd

In [7]:
pd.read_csv('machine_downtime.csv')

df = pd.read_csv('machine_downtime.csv')

In [8]:
df.head()

,ID_Kejadian,Tanggal_Kejadian,ID_Mesin,Usia_Mesin_Tahun,Penyebab_Downtime,Durasi_Downtime_Menit,Beban_Kerja_Harian_Persen,Shift_Kejadian,Biaya_Perbaikan_Ribu_Rupiah
0,DT0001,2025-09-03,M08,10.2,Kerusakan Elektrikal,70.5,98.2,Malam,NaN
1,DT0002,2025-11-11,M10,6.4,Kerusakan Mekanis,57.3,77.6,Malam,1149.0
2,DT0003,2025-09-21,M05,7.2,Kerusakan Mekanis,59.9,43.4,Pagi,820.0
3,DT0004,2025-08-23,M06,12.9,Kerusakan Mekanis,79.8,69.8,Siang,1757.0
4,DT0005,2026-01-14,M07,8.5,Kerusakan Mekanis,64.4,100.0,Pagi,787.0

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   ID_Kejadian                  520 non-null    str
 1   Tanggal_Kejadian             520 non-null    str
 2   ID_Mesin                     520 non-null    str
 3   Usia_Mesin_Tahun             520 non-null    float64
 4   Penyebab_Downtime            520 non-null    str
 5   Durasi_Downtime_Menit        520 non-null    float64
 6   Beban_Kerja_Harian_Persen    520 non-null    float64
 7   Shift_Kejadian               520 non-null    str
 8   Biaya_Perbaikan_Ribu_Rupiah  427 non-null    float64
dtypes: float64(4), str(5)
memory usage: 59.2 KB

In [10]:
df.describe()

,Usia_Mesin_Tahun,Durasi_Downtime_Menit,Beban_Kerja_Harian_Persen,Biaya_Perbaikan_Ribu_Rupiah
count,520.000000,520.000000,520.000000,427.000000
mean,7.645577,62.411538,71.403654,1053.231850
std,3.437073,9.724885,14.249577,401.454071
min,-8.600000,42.800000,20.000000,158.000000
25%,6.200000,56.600000,62.400000,774.000000
50%,7.100000,59.600000,71.550000,1048.000000
75%,10.500000,71.500000,81.300000,1321.000000
max,13.400000,81.600000,100.000000,2186.000000

In [11]:
df.dropna()

,ID_Kejadian,Tanggal_Kejadian,ID_Mesin,Usia_Mesin_Tahun,Penyebab_Downtime,Durasi_Downtime_Menit,Beban_Kerja_Harian_Persen,Shift_Kejadian,Biaya_Perbaikan_Ribu_Rupiah
1,DT0002,2025-11-11,M10,6.4,Kerusakan Mekanis,57.3,77.6,Malam,1149.0
2,DT0003,2025-09-21,M05,7.2,Kerusakan Mekanis,59.9,43.4,Pagi,820.0
3,DT0004,2025-08-23,M06,12.9,Kerusakan Mekanis,79.8,69.8,Siang,1757.0
4,DT0005,2026-01-14,M07,8.5,Kerusakan Mekanis,64.4,100.0,Pagi,787.0
5,DT0006,2025-10-03,M07,8.6,Kerusakan Mekanis,64.8,67.4,Malam,944.0
...,...,...,...,...,...,...,...,...,...
514,DT0515,2026-01-02,M01,6.5,Kekurangan Bahan Baku,57.3,55.7,Pagi,1484.0
515,DT0516,2025-11-08,M06,12.7,Pergantian Alat (Tooling Change),79.2,58.7,Malam,938.0
517,DT0518,2025-11-28,M09,5.8,Kerusakan Mekanis,54.9,52.7,Malam,1264.0
518,DT0519,2025-08-22,M03,3.0,Kesalahan Operator,45.3,46.6,Malam,1152.0
519,DT0520,2025-12-24,M01,5.9,Kerusakan Mekanis,55.4,79.6,Pagi,567.0